<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cl</string>
	</array>
	<key>name</key>
	<string>Cool</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>--</string>
			<key>comment</key>
			<string>Line Comments</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.cool</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(\*</string>
			<key>comment</key>
			<string>Block Comments</string>
			<key>end</key>
			<string>\*\)</string>
			<key>name</key>
			<string>comment.block.cool</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)"</string>
			<key>comment</key>
			<string>Strings</string>
			<key>end</key>
			<string>(?&lt;!\\)"</string>
			<key>name</key>
			<string>string.cool</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Escape Sequences</string>
					<key>match</key>
					<string>\\(n|t)</string>
					<key>name</key>
					<string>constant.character.escape.cool</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.cool</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.cool</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.cool</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.cool</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Class definition</string>
			<key>match</key>
			<string>\b((?i:class))\s+([A-Z][A-Za-z0-9_]*)(\s+((?i:inherits))\s+([A-Z][A-Za-z0-9_]*))?\b</string>
			<key>name</key>
			<string>definition.class.cool</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.cool</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.cool</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type.cool</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.cool</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>storage.type.cool</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>storage.type.cool</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Method definition</string>
			<key>match</key>
			<string>\b([a-z][A-Za-z0-9_]*)\s*\(\s*(?:([a-z][A-Za-z0-9_]*)\s*:\s*([A-Z][A-Za-z0-9_]*))?(?:\s*,\s*([a-z][A-Za-z0-9_]*)\s*:\s*([A-Z][A-Za-z0-9_]*))*\s*\)\s*:\s*([A-Z][A-Za-z0-9_]*)\b</string>
			<key>name</key>
			<string>definition.method.cool</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.cool</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.cool</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.cool</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Integer literal</string>
			<key>match</key>
			<string>\b([1-9][0-9]*)\b</string>
			<key>name</key>
			<string>number.cool</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Boolean Constants</string>
			<key>match</key>
			<string>\b((t(?i:rue))|(f(?i:alse)))</string>
			<key>name</key>
			<string>constant.language.cool</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Language operators</string>
			<key>match</key>
			<string>(=&gt;|&lt;-|&lt;=|@|/|&lt;|-|~|=|\+|\*)</string>
			<key>name</key>
			<string>keyword.operator.cool</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control flow tokens</string>
			<key>match</key>
			<string>\b(?i:case|class|else|esac|fi|if|in|inherits|isvoid|let|loop|new|not|of|pool|then|while)\b</string>
			<key>name</key>
			<string>keyword.control.cool</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Type identifier</string>
			<key>match</key>
			<string>\b([A-Z][A-Za-z0-9_]*)</string>
			<key>name</key>
			<string>storage.type.cool</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cool</string>
	<key>uuid</key>
	<string>963eee5d-986b-456c-8fbd-d81e05548a88</string>
</dict>
</plist>
